# Generated by Django 4.0.4 on 2022-05-11 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_remove_user_company_name_remove_user_last_contact_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
    ]
