# Generated by Django 4.0.4 on 2022-05-11 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_remove_customer_status_remove_employee_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='login.employee'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(default=[('SALES', 'SALES'), ('SUPPORT', 'SUPPORT'), ('MANAGER', 'MANAGER'), ('CUSTOMER', 'CUSTOMER')], max_length=10, null=True),
        ),
    ]
