# Generated by Django 4.0.4 on 2022-05-11 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_employee_manager_alter_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='sales_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='login.employee'),
        ),
    ]
