# Generated by Django 4.0.4 on 2022-05-17 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_alter_customer_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['status']},
        ),
    ]
