# Generated by Django 4.0.4 on 2022-06-02 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='sales_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prospect_sales', to='login.employee'),
        ),
        migrations.AddField(
            model_name='event',
            name='contract_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.contract', unique=True),
        ),
        migrations.AddField(
            model_name='event',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_customer', to='login.customer'),
        ),
        migrations.AddField(
            model_name='event',
            name='providers',
            field=models.ManyToManyField(blank=True, null=True, to='app.provider'),
        ),
        migrations.AddField(
            model_name='event',
            name='support_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='event_support', to='login.employee'),
        ),
        migrations.AddField(
            model_name='contract',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract_customer', to='login.customer'),
        ),
        migrations.AddField(
            model_name='contract',
            name='sales_contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract_sales', to='login.employee'),
        ),
    ]
