# Generated by Django 4.0.4 on 2022-05-09 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_contract_customer_employee_event_prospect_provider_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provider',
            old_name='name',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='provider',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
