# Generated by Django 4.0.4 on 2022-05-12 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_alter_prospect_last_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='support_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='event_support', to=settings.AUTH_USER_MODEL),
        ),
    ]
