# Generated by Django 4.0.4 on 2022-05-12 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_event_support_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='signed',
            new_name='customer_signature',
        ),
        migrations.AddField(
            model_name='contract',
            name='employee_signature',
            field=models.BooleanField(default=False),
        ),
    ]
