# Generated by Django 4.0.4 on 2022-05-12 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_signed_contract_customer_signature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='signed',
            field=models.BooleanField(default=False),
        ),
    ]
