# Generated by Django 4.0.4 on 2022-05-12 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_contract_signed'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='history',
            field=models.TextField(blank=True, null=True),
        ),
    ]
