# Generated by Django 4.0.4 on 2022-05-16 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_alter_customer_sales_contact'),
        ('app', '0007_contract_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='sales_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prospect_sales', to='login.employee'),
        ),
    ]
