# Generated by Django 4.0.4 on 2022-05-16 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_alter_customer_sales_contact'),
        ('app', '0008_alter_prospect_sales_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_customer', to='login.customer'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='sales_contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract_sales', to='login.employee'),
        ),
        migrations.AlterField(
            model_name='event',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_customer', to='login.customer'),
        ),
        migrations.AlterField(
            model_name='event',
            name='support_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='event_support', to='login.employee'),
        ),
    ]
