# Generated by Django 4.0.4 on 2022-05-17 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_contract_customer_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prospect',
            options={'ordering': ['last_contact']},
        ),
    ]
