# Generated by Django 4.0.4 on 2022-05-17 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_prospect_converted'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
