# Generated by Django 4.0.4 on 2022-05-17 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_prospect_first_name_alter_prospect_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='email',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
