# Generated by Django 4.0.4 on 2022-05-18 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_event_description_alter_event_due_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='history',
        ),
    ]
