# Generated by Django 4.0.4 on 2022-05-23 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_alter_customer_company_name_and_more'),
        ('app', '0021_remove_contract_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='sales_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prospect_sales', to='login.employee'),
        ),
    ]
