# Generated by Django 4.0.4 on 2022-05-25 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_prospect_sales_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ['modified_date']},
        ),
    ]
