# Generated by Django 4.0.4 on 2022-05-25 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_contract_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ['-modified_date']},
        ),
    ]
