# Generated by Django 4.0.4 on 2022-05-26 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_event_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='providers',
            field=models.ManyToManyField(blank=True, null=True, to='app.provider'),
        ),
    ]
