# Generated by Django 4.0.4 on 2022-05-27 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_alter_user_email_alter_user_first_name_and_more'),
        ('app', '0026_alter_event_providers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract_customer', to='login.customer'),
        ),
        migrations.AlterField(
            model_name='event',
            name='contract_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.contract', unique=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='sales_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prospect_sales', to='login.employee'),
        ),
    ]
